config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "pages/home", to: "pages#home"
  resources :recipes
  get '/signup', to: 'chefs#new'
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :chefs, except: [:new]
  resources :ingredients, except: [:destroy]
  resources :recipes do
    resources :comments, only: [:create]
      member do
        post 'like'
      end
  end

  mount ActionCable.server => "/cable"

  get "/chat", to: "chatrooms#show"

  resources :messages, only: [:create]
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "My Recipes", root_path, class: "nav-link active", id: "logo"%>
    </li>
    <li class="nav-item pull-right">
      <%= link_to "Chefs", chefs_path, class: "nav-link" %>
    </li>
    <li class="nav-item pull-right">
      <%= link_to "All Recipes", recipes_path, class: "nav-link"%>
    </li>
    <li class="dropdown nav-item pull-right">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Ingredients <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "All Ingredients", ingredients_path %></li>
        <% Ingredient.all.each do |ingredient| %>
        <li><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
        <% end %>
        <% if logged_in? && current_chef.admin? %>
          <li role="separator" class="divider"></li>
          <li><%= link_to "New Ingredient", new_ingredient_path %></li>
        <% end %>
      </ul>
    </li>
    <% if logged_in? %>
    <li class="nav-item pull-right">
      <%= link_to "Create a new recipe", new_recipe_path, class: "nav-link"%>
    </li>
    <li class="nav-item pull-right">
      <%= link_to "ChefChat", chat_path %>
    </li>
    <%end%>
    <% if logged_in? %>
    <li class="dropdown nav-item pull-right">
      <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"
      role="button" aria-haspopup="true" aria-expanded="false">
      <%= current_chef.name.capitalize %>'s Profile
      <%= "Admin" if current_chef.admin? %>
      <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li class="nav-item pull-right"><%= link_to "View your profile", chef_path(current_chef), class: "nav-link" %></li>
        <li class="nav-item pull-right"><%= link_to "Edit your profile", edit_chef_path(current_chef), class: "nav-link" %></li>
        <li role="separator" class="divider"></li>
        <li class="nav-item pull-right"><%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %></li>
      </ul>
      </li>
      <% else %>
      <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_navbar2.html.erb
<div class="nav">
  <div class="nav-header">
    <div class="nav-title">
      <%= link_to "My Recipes", root_path, class: "nav-link active", id: "logo"%>
    </div>
  </div>
  <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
  <input type="checkbox" id="nav-check">
  <div class="nav-links ml-auto">
    <% if logged_in? %>
      <li class="dropdown pullright">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"
      role="button" aria-haspopup="true" aria-expanded="false">
      <%= current_chef.name.capitalize %>'s Profile
      <%= "Admin" if current_chef.admin? %>
      <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li class="nav-item pull-right"><%= link_to "View your profile", chef_path(current_chef), class: "nav-link" %></li>
        <li class="nav-item pull-right"><%= link_to "Edit your profile", edit_chef_path(current_chef), class: "nav-link" %></li>
        <li role="separator" class="divider"></li>
        <li class="nav-item pull-right"><%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %></li>
      </ul>
      </li>
      <% else %>
      <%= link_to "Log in", login_path, class: "nav-link" %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "ChefChat", chat_path %>
    <%end%>
    <%= link_to "Chefs", chefs_path, class: "nav-link" %>
    <%= link_to "All Recipes", recipes_path, class: "nav-link"%>
    <% if logged_in? %>
      <%= link_to "Create a new recipe", new_recipe_path, class: "nav-link"%>
    <%end%>
    <li class="dropdown pullright">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Ingredients <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to "All Ingredients", ingredients_path %></li>
      <% Ingredient.all.each do |ingredient| %>
      <li><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
      <% end %>
      <% if logged_in? && current_chef.admin? %>
        <li role="separator" class="divider"></li>
        <li><%= link_to "New Ingredient", new_ingredient_path %></li>
      <% end %>
    </ul>
    </li>
  </div>
</div>

app/views/layouts/_notices.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar2" %>
    <%= render 'layouts/notices' %>
    <div class="container">
      <%= yield %>
    </div>
    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <%= link_to "Back to top", root_path, style: "color: white;"%>
        </p>
        <p>&copy; JustVirtual 2018</p>
      </div>
    </footer>
  </body>
</html>